name: Adblack_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Rule
      run: |
        echo ä¸‹è½½anti-AD
        curl -kfSL -o Adblack.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
        echo ä¸‹è½½è‡ªç”¨é»‘åå•
        curl -kfSL -o Blacklist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Blacklist.txt
        echo ä¸‹è½½è‡ªç”¨ç™½åå•
        curl -kfSL -o Allowlist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Allowlist.txt

    - name: Process Rule File
      run: |
        sed -i '/^[#!]/d' Adblack.txt
        echo å¤„ç†é»‘åå•ï¼Œæ·»åŠ è¿›ä¸»è§„åˆ™
        sed -i -e '/^[#!]/d' -e '/^[[:space:]]*$/d' -e 's/[||^@]//g' -e 's/^/DOMAIN-SUFFIX,/' Blacklist.txt
        cat Blacklist.txt >> Adblack.txt
        echo å¤„ç†ç™½åå•ï¼Œåˆ é™¤å¯¹åº”è§„åˆ™
        sed -i -e '/^[#!]/d' -e '/^[[:space:]]*$/d' -e 's/[||^@]//g' -e 's/^/DOMAIN-SUFFIX,/' Allowlist.txt
        while IFS= read -r line; do
          sed -i "/$line/d" Adblack.txt
        done < Allowlist.txt

        echo æ·»åŠ æ³¨é‡Šæ•°é‡æ—¶é—´å¤‡æ³¨
        version=$(TZ=Asia/Shanghai date '+%Yå¹´%mæœˆ%dæ—¥%H:%M:%S')
        count=$(grep -E 'DOMAIN-SUFFIX' Adblack.txt | wc -l)
        sed -i "1i\\# å†…å®¹: ğŸš« å¹¿å‘Šè¿‡æ»¤ è§„åˆ™é›†\\n# å¤‡æ³¨: ä»¥anti-ADä¸ºåŸºç¡€ï¼Œæ·»åŠ è‡ªç”¨è§„åˆ™ï¼ŒåŸä½œè€…: https://github.com/privacy-protection-tools/anti-AD\\n# æ›´æ–°: $version\\n# æ•°é‡: $countæ¡" Adblack.txt
        echo åˆ›å»ºDOMAIN-SETæ ¼å¼è§„åˆ™
        cp Adblack.txt Adblack2.txt
        sed -i 's/DOMAIN-SUFFIX,/\./g' Adblack2.txt



    - name: Commit And Push
      run: |
        git config --global user.email "long632450362@qq.com" && git config --global user.name "Bot"
        git add * && git commit -m "è‡ªåŠ¨æ›´æ–°:$(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2
